# Coursera Finance Specialisation (U Michigan)
# Week 4 -- Decision Making and Cash Flows
# Quiz
#
# Joe Nguyen | 11 Oct, 2015

rm(list = ls())
graphics.off()

# Change working directory
dirBase <- "/home/joe/Documents/01-coursera/02-finance"
dirWorking <- "/01-tvm/r-code"
setwd(paste0(dirBase, dirWorking))

# Generic finance functions
source(paste0(dirBase, dirWorking, "/func_finance.R"))


## Question 1
# (5 points) The NPV rule is always preferred when making a decision between two mutually exclusive projects.
#
# FALSE; IRR + r should be considered. Also, annuity ($/period) can be considered if the two projects have different time durations.


## Question 2
# (10 points) The city of Middleville is considering offering public bus service. Setting up the service will cost the city $1.7M (where M stands for million). The useful life of the buses is 18 years. Annual maintenance of the buses would cost $135,000 per year and they would need a major overhaul in year 10 that will cost a total of $890,000. This overhaul is in addition to the annual maintenance. Annual labor and administrative costs will begin at $170,000 in year 1 and grow at 1.0% per year thereafter. The buses will generate a revenue of $305,000 in year 1 and it will grow at 4.0% per year thereafter. Reduced parking requirements and other benefits generated by the project will save the city $405,000 per year. The salvage value (price the city can get in the future after maintenance) of the used buses in year 18 is expected to be $480,000. What is the NPV of the bus proposal? The city does not pay taxes and the discount rate is 6.3%. Assume that all cash flows except initial investments happen at the end of the year and you are strongly encouraged to use a spreadsheet to solve this problem.

# Project cost
cost <- 1.7e6
n <- 18

# Yearly maintainance cost
cVec <- rep(-135e3, n)

# Overhaul cost in year 10
cVec[10] <- cVec[10] - 890e3

# Year 1 labour and admin cost
admin.cost <- -170e3
admin.r <- 0.01

# Year 1 revenue
rev.year1 <- 305e3
rev.r <- 0.04

# Yearly savings generated by project
savingVec <- rep(405e3, n)

# Salvage value of buses at end of year 18
savingVec[18] <- savingVec[18] + 480e3

r <- 0.063

# SOLUTION - determine all cashflows ($ value for that year, do not discount)
admin.costVec <- rep(0,n)
rev.valVec <- rep(0,n)

for (i in 1:n) {
    admin.costVec[i] <- FV(admin.cost, admin.r, i-1)
    rev.valVec[i] <- FV(rev.year1, rev.r, i-1)
}

# NPV
NPV(cost, cVec + admin.costVec + rev.valVec + savingVec, r)


## Question 3
# (5 points) Alpha Inc. has the following two projects that it is considering, and it wants to choose one. Project A has an investment outlay/expense today of $840, and its cash flows over the next three years are $380, $510, and $550. Project B has an outlay of $1,680, and cash flows of $800, $990, and $1,200. Which project should Alpha choose? (You can assume no taxes.)
a.cost <- 840
a.cVec <- c(380,510,550)

b.cost <- 1680
b.cVec <- c(800,990,1200)

IRR(a.cost, a.cVec)
IRR(b.cost, b.cVec)

NPV(a.cost, a.cVec, 0)
NPV(b.cost, b.cVec, 0)

# Choose project B since it always gives higher NPV for r < 32.6% (larger IRR - IFF of b)


## Question 4
# (10 points) GE has the following two projects that it is considering; it can choose only one. Project A has an investment outlay/expense today of $11.0M, and its cash flows over the next three years are $4.8M, $4.8M, and $5.6M. Project B has an outlay of $11.0M, and cash flows of $0M, $0M, and $15.5M. Which project should GE choose if the cost of capital for similar projects is 3.00%?
a.cost <- 11
a.cVec <- c(4.8, 4.8, 5.6)

b.cost <- 11
b.cVec <- c(0, 0, 15.5)

r <- 0.03

NPV(a.cost, a.cVec, r)
NPV(b.cost, b.cVec, r)

IRR(a.cost, a.cVec)
IRR(b.cost, b.cVec)

rVec <- seq(0,1, by = 0.01)
a.npv <- NPV(a.cost, a.cVec, rVec)
b.npv <- NPV(b.cost, b.cVec, rVec)

plot_npv_r(rVec, a.npv)
plot_npv_r(rVec, b.npv)

# ga <- plot_npv_r(rVec, a.npv)
# gb <- plot_npv_r(rVec, b.npv)
# ga + gb


## Question 5
# (5 points) All else equal, purchasing inventory on credit will increase the value of a firm's net working capital.
#
# TRUE; purchasing inventory increases working capital


## Question 6
# (5 points) Last year your firm had revenue of $20.5 million, cost of goods sold (COGS) of $13.5 million, Selling, General, & Administration costs (SG&A) of $2.5 million, Account Receivables (AR) of $6.5 million, Account Payables (AP) of $5.5 million and Inventory of $5.5 million. What will be the free cash flow this year if you boost revenue 6.0% and AR 12.5%, while holding COGS growth to 4.0% and everything else remains the same as last year? Assume no taxes and no new capital expenditures. You are encouraged to use a spreadsheet even for this specific type of question.
rev <- 20.5e6
cogs <- 13.5e6
sga <- 2.5e6
ar <- 6.5e6
ap <- 5.5e6
invtry <- 5.5e6

rev1 <- FV(rev, 0.06, 1)
ar1 <- FV(ar, 0.125, 1)
cogs1 <- FV(cogs, 0.04, 1)

# Free cash flow this year
c <- rev1 - cogs1 - sga - (ar1 - ar); c

# Version 1
# Last year your firm had revenue of $27.5 million, cost of goods sold (COGS) of $17.5 million, Selling, General, & Administration costs (SG&A) of $3.5 million, Account Receivables (AR) of $8.5 million, Account Payables (AP) of $7.0 million and Inventory of $5.5 million. What will be the free cash flow this year if you boost revenue 3.5% and AR 9.5%, while holding COGS growth to 2.5% and everything else remains the same as last year? Assume no taxes and no new capital expenditures. You are encouraged to use a spreadsheet even for this specific type of question.
rev <- 27.5e6
cogs <- 17.5e6
sga <- 3.5e6
ar <- 8.5e6
ap <- 7e6
invtry <- 5.5e6

rev1 <- FV(rev, 0.035, 1)
ar1 <- FV(ar, 0.095, 1)
cogs1 <- FV(cogs, 0.025, 1)

c <- (rev1 - rev) - (cogs1 - cogs) - (ar1 - ar); c
c <- rev1 - cogs1 - sga - (ar1 - ar); c


## Question 7
# (15 points) Silver Bear Golf (SBG) is a manufacturer of top quality golf clubs with a specialty of putters. Currently, each putter they sell brings in $250 of revenue at a cost of $160. This past year, they sold 1,100 putters and they expect this number to grow each year by 12.5% until this model becomes obselete after 15 more years. The foreman at the SBG factory recently brought to your attention a new technology that could lower the cost of production. This technology requires an upfront fixed investment of $162,000 and has the capacity to produce all the putters you want to sell per year at a unit cost of $142. There is no increased working capital need due to this new technology, and no value of the machine/technology after 15 years. What is the NPV of investing in the new technology? Ignore taxes and assume a discount rate of 10.0%. (Hint: Think incrementally; the difference between the world without and with this new technology! Also, ignoring taxes will be a big help if you think right. You are strongly encouraged to use a spreadsheet.)
#
# Difference per period (year) with (b) and without (a) new technology
rev <- 250
a.cost <- 160
b.cost <- 142
item.tot <- 1100
item.growth <- 0.125
n <- 15
r <- 0.1

b.cost0 <- 162e3

# Determine cash flows difference over periods (don't discount r here)
profitDiff <- rev - (b.cost - a.cost)
cDiff <- rep(0, n)
# for (i in 1:n) {
#     cDiff[i] <- 
# }











