# Coursera Finance Specialisation (U Michigan)
# Week 4 -- Decision Making and Cash Flows
# Quiz - attempt 2
#
# Joe Nguyen | 14 Oct, 2015

rm(list = ls())
# graphics.off()
# dev.off()

# Change working directory
dirBase <- "/home/joe/Documents/01-coursera/02-finance"
dirWorking <- "/01-tvm/r-code"
setwd(paste0(dirBase, dirWorking))

# Generic finance functions
source(paste0(dirBase, dirWorking, "/func_finance.R"))


## Question 1
# (5 points) The NPV rule is always preferred when making a decision between two mutually exclusive projects.
#
# FALSE; IRR + r should be considered. Also, annuity ($/period) can be considered if the two projects have different time durations.
#
# change to TRUE, since 1) annuity ($/period) is derived from NPV, and 2) IRR + r does not account for projects with different timelines.


## Question 2
# (10 points) The city of Middleville is considering offering public bus service. Setting up the service will cost the city $1.7M (where M stands for million). The useful life of the buses is 18 years. Annual maintenance of the buses would cost $135,000 per year and they would need a major overhaul in year 10 that will cost a total of $890,000. This overhaul is in addition to the annual maintenance. Annual labor and administrative costs will begin at $170,000 in year 1 and grow at 1.0% per year thereafter. The buses will generate a revenue of $305,000 in year 1 and it will grow at 4.0% per year thereafter. Reduced parking requirements and other benefits generated by the project will save the city $405,000 per year. The salvage value (price the city can get in the future after maintenance) of the used buses in year 18 is expected to be $480,000. What is the NPV of the bus proposal? The city does not pay taxes and the discount rate is 6.3%. Assume that all cash flows except initial investments happen at the end of the year and you are strongly encouraged to use a spreadsheet to solve this problem.

# Project cost
cost <- 1.7e6
n <- 18

# Yearly maintainance cost
cVec <- rep(-135e3, n)

# Overhaul cost in year 10
cVec[10] <- cVec[10] - 890e3

# Year 1 labour and admin cost
admin.cost <- -170e3
admin.r <- 0.01

# Year 1 revenue
rev.year1 <- 305e3
rev.r <- 0.04

# Yearly savings generated by project
savingVec <- rep(405e3, n)

# Salvage value of buses at end of year 18
savingVec[18] <- savingVec[18] + 480e3

r <- 0.063

# SOLUTION - determine all cashflows ($ value for that year, do not discount)
admin.costVec <- rep(0,n)
rev.valVec <- rep(0,n)

for (i in 1:n) {
    admin.costVec[i] <- FV(admin.cost, admin.r, i-1)
    rev.valVec[i] <- FV(rev.year1, rev.r, i-1)
}

# NPV
NPV(cost, cVec + admin.costVec + rev.valVec + savingVec, r)


## Question 3
# (5 points) Alpha Inc. has the following two projects that it is considering, and it wants to choose one. Project A has an investment outlay/expense today of $1,010, and its cash flows over the next three years are $480, $640, and $740. Project B has an outlay of $2,020, and cash flows of $950, $1,260, and $1,320. Which project should Alpha choose? (You can assume no taxes.)
a.cost <- 1010
a.cVec <- c(480,640,740)

b.cost <- 2020
b.cVec <- c(950,1260,1320)

a.irr <- IRR(a.cost, a.cVec); a.irr
b.irr <- IRR(b.cost, b.cVec); b.irr

NPV(a.cost, a.cVec, 0)
NPV(b.cost, b.cVec, 0)

rVec <- seq(0,1, by = 0.01)
a.npv <- NPV(a.cost, a.cVec, rVec)
b.npv <- NPV(b.cost, b.cVec, rVec)

plot_npv_r(rVec, a.npv, a.irr)
plot_npv_r(rVec, b.npv, b.irr, color = 2, newplot = FALSE)

# Choose project B since it always gives higher NPV for r < 32.6% (larger IRR - IRR of b)
#
# change to "Cannot make a choice based on information" because we don't know value of r.


## Question 4
# (10 points) GE has the following two projects that it is considering; it can choose only one. Project A has an investment outlay/expense today of $11.0M, and its cash flows over the next three years are $4.8M, $4.8M, and $5.6M. Project B has an outlay of $11.0M, and cash flows of $0M, $0M, and $15.5M. Which project should GE choose if the cost of capital for similar projects is 3.00%?
a.cost <- 11
a.cVec <- c(4.8, 4.8, 5.6)

b.cost <- 11
b.cVec <- c(0, 0, 15.5)

r <- 0.03

NPV(a.cost, a.cVec, r)
NPV(b.cost, b.cVec, r)

a.irr <- IRR(a.cost, a.cVec); a.irr
b.irr <- IRR(b.cost, b.cVec); b.irr

rVec <- seq(0,1, by = 0.01)
a.npv <- NPV(a.cost, a.cVec, rVec)
b.npv <- NPV(b.cost, b.cVec, rVec)

plot_npv_r(rVec, a.npv, a.irr)
plot_npv_r(rVec, b.npv, b.irr, color = 2, newplot = FALSE)

# Choose project A as a.npv > b.npv for r = 3.00%


## Question 5
# (5 points) All else equal, purchasing inventory on credit will increase the value of a firm's net working capital.
#
# FALSE; while purchasing inventory increases working capital, purchasing on credit does not because credit can be paid in future


## Question 6
# (5 points) Last year your firm had revenue of $20.5 million, cost of goods sold (COGS) of $13.5 million, Selling, General, & Administration costs (SG&A) of $2.5 million, Account Receivables (AR) of $6.5 million, Account Payables (AP) of $5.5 million and Inventory of $5.5 million. What will be the free cash flow this year if you boost revenue 6.0% and AR 12.5%, while holding COGS growth to 4.0% and everything else remains the same as last year? Assume no taxes and no new capital expenditures. You are encouraged to use a spreadsheet even for this specific type of question.
rev <- 20.5e6
cogs <- 13.5e6
sga <- 2.5e6
ar <- 6.5e6
ap <- 5.5e6
invtry <- 5.5e6

rev1 <- FV(rev, 0.06, 1)
ar1 <- FV(ar, 0.125, 1)
cogs1 <- FV(cogs, 0.04, 1)

# Free cash flow this year
c <- rev1 - cogs1 - sga - (ar1 - ar); c

# Version 1
# Last year your firm had revenue of $27.5 million, cost of goods sold (COGS) of $17.5 million, Selling, General, & Administration costs (SG&A) of $3.5 million, Account Receivables (AR) of $8.5 million, Account Payables (AP) of $7.0 million and Inventory of $5.5 million. What will be the free cash flow this year if you boost revenue 3.5% and AR 9.5%, while holding COGS growth to 2.5% and everything else remains the same as last year? Assume no taxes and no new capital expenditures. You are encouraged to use a spreadsheet even for this specific type of question.
rev <- 27.5e6
cogs <- 17.5e6
sga <- 3.5e6
ar <- 8.5e6
ap <- 7e6
invtry <- 5.5e6

rev1 <- FV(rev, 0.035, 1)
ar1 <- FV(ar, 0.095, 1)
cogs1 <- FV(cogs, 0.025, 1)

c <- (rev1 - rev) - (cogs1 - cogs) - (ar1 - ar); c
c <- rev1 - cogs1 - sga - (ar1 - ar); c


## Question 7
# (15 points) Silver Bear Golf (SBG) is a manufacturer of top quality golf clubs with a specialty of putters. Currently, each putter they sell brings in $240 of revenue at a cost of $160. This past year, they sold 1,300 putters and they expect this number to grow each year by 10.5% until this model becomes obselete after 9 more years. The foreman at the SBG factory recently brought to your attention a new technology that could lower the cost of production. This technology requires an upfront fixed investment of $115,000 and has the capacity to produce all the putters you want to sell per year at a unit cost of $114. There is no increased working capital need due to this new technology, and no value of the machine/technology after 9 years. What is the NPV of investing in the new technology? Ignore taxes and assume a discount rate of 9.5%. (Hint: Think incrementally; the difference between the world without and with this new technology! Also, ignoring taxes will be a big help if you think right. You are strongly encouraged to use a spreadsheet.)
#
# Assumptions:
# 1) No inflation for revenue and costs
# 2) 1100 putters sold in year 0; find cash flows for years 1 to 15; NPV at year 0
#
# Difference per period (year) with (b) and without (a) new technology
rev <- 240
a.cost <- 160
b.cost <- 114
item.tot <- 1300
item.growth <- 0.105
n <- 9
r <- 0.095

b.cost0 <- 115e3

# Determine cash flows difference over periods (don't discount r here; don't worry about rounding)
profitDiff <- (a.cost - b.cost)
cDiff <- rep(0, n)
for (i in 1:n) {
    cDiff[i] <- profitDiff * FV(item.tot, item.growth, i)
}

NPV(b.cost0, cDiff, r)


## Question 8
# (15 points) Fresh off the excitement of the 2012 London Olympic Games, you decide that you want your firm to take advantage of the profits to be made for the 2016 games in Rio de Jeneiro. To do so you plan to open a factory in Brazil. After examining the idea, your CFO projects revenues next year (2013) to be $16 million and costs to be $7 million. Both of these are expected to grow at a rate of 21.0% per year as the excitement for the games builds. Your firm faces a 35% tax rate, a 10.0% discount rate and you can depreciate your new investment using the straight line method over the four years leading up to the games, at which point the value of the venture moving forward will be $5 million. This $5 million is the after-tax terminal value that is in year 4 (that is, 2016) dollars and is the PV of all cash flows year 5 and beyond. The capital expenditure of this project is $11 million. What is the NPV of the project? Assume that you have no significant working capital costs.
#
# CASH FLOWS FROM PROJECT:
# +revenues - costs of good sold - admin costs - depreciations = operating profits;
# operating profits - cash taxes (on operating profits) = net operating profits after tax;
# net operating profits + depreciation - capex - increases in working capital (acc rec - acc payables) =
# cash flows from project
#
prj.rev <- 16e6
prj.cost <- 7e6
prj.r <- 0.21

tax.r <- 0.35
r <- 0.1
n <- 4

termVal <- 5e6
capex <- 11e6

# Depreciation (straight line method over the four years)
deprec <- capex / n

# Periodic cash flows (in period $ values)
cVec <- rep(0,n)

for (i in 1:n) {
    # Operating profit = revenue - cost - depreciation
    operProfit <- FV(prj.rev, prj.r, i-1) - FV(prj.cost, prj.r, i-1) - deprec
    
    # Net operating profit after tax
    nopat <- (1 - tax.r) * operProfit
    
    # Cash flow
    cVec[i] <- nopat + deprec
}

# NPV
NPV(capex, cVec, r) + PV(termVal, r, n)


## Question 9
# (15 points) Walmart is considering opening a small experimental store in New York City. A store is expected to have a long economic life, but the valuation horizon is 18 years. The store in New York is likely to generate revenues of $39M in the first year and then it grows at 6.5%. But the costs of running the business are high because the margins on all the products sold are low. (It is a volume business!) The cost of goods sold is $10M in year 1 and it is expected to grow at 3.0% per year thereafter. Selling and administration costs are likely to be $0.8M every year as it is a small store. The tax rate is 35%. Walmart is so good at managing its stores that working capital increases can be assumed to be negligible. But since New York City is an expensive place, Walmart will have to invest $225M in purchasing a building (with land) even though it is a much smaller property than a usual Walmart store. The good news is that this outlay can be straight line depreciated over 18 years. Also, Walmart has estimated that the after-tax terminal value in year 18 dollars is $75M. This value is the present value of all cash flows in year 19 and beyond. What is the NPV of opening this new store if the appropriate discount rate is 6.0%? (Again, all cash flows except initial investments happen at the end of the year. You are strongly encouraged to use a spreadsheet.)
rev <- 39e6
rev.g <- 0.065
cost <- 10e6
cost.g <- 0.03
admin <- 0.8e6
tax <- 0.35
capex <- 225e6
r <- 0.06
n <- 18
deprec <- capex / n
termVal <- 75e6

# Periodic cash flows (in period $ values)
cVec <- rep(0,n)

for (i in 1:n) {
    # Operating profit
    op <- FV(rev, rev.g, i-1) - FV(cost, cost.g, i-1) - admin - deprec
    
    # Net operating profit after tax
    nopat <- (1 - tax) * op
    
    # Cash flow
    cVec[i] <- nopat + deprec
}

# NPV
NPV(capex, cVec, r) + PV(termVal, r, n)


## Question 10
# (15 points) Springfield Ironworks (SI) recently had their furnace break down and they need to quickly purchase a new one to minimize the disruption in their production. They can either choose a high quality furnace (H) that costs $105,000 with $2,500 of annual maintenance costs for the 7-year life of the furnace, or a low quality furnace (L) that costs $50,000 with $6,500 in annual maintenance costs for the 4-year life of the furnace. Which furnace should SI choose? What is the annualized cost of their choice? Assume a discount rate of 7.0%, and ignore all taxes.
h.capex <- 105e3
h.mtCost <- 2500
h.n <- 7

l.capex <- 50e3
l.mtCost <- 6500
l.n <- 4

r <- 0.07

h.npv <- NPV(h.capex, rep(-h.mtCost, h.n), r)
annuity_c(0, h.npv, r, h.n)

l.npv <- NPV(l.capex, rep(-l.mtCost, l.n), r)
annuity_c(0, l.npv, r, l.n)

